### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by gitsoft** [poxet/GitBitch#1]
For some reason an error is thrown on line 59 in ListenerAgent when the projects is started locally.
ClownCrew.GitBitch.Client\Agents\ListenerAgent.cs:line 59
_speechRecognitionEngine.SetInputToDefaultAudioDevice();

Steps to repoduce:
Clone project on a computer with any prior voice installations
Start the solution with GitBitch.Client as startup project.

Error thrown:
Cannot find the requested data item, such as a data key or value.
Source:
System.Speech

Full stacktrace:
   at System.Speech.Recognition.RecognizerBase.SetInputToDefaultAudioDevice()
   at System.Speech.Recognition.SpeechRecognitionEngine.SetInputToDefaultAudioDevice()
   at ClownCrew.GitBitch.Client.Agents.ListenerAgent`1..ctor(IEventHub eventHub, IEnumerable`1 alternatives) in c:\gitext\GitBitch\ClownCrew.GitBitch.Client\Agents\ListenerAgent.cs:line 59
   at ClownCrew.GitBitch.Client.Agents.QuestionAgent.<AskAsync>d__8`1.MoveNext() in c:\gitext\GitBitch\ClownCrew.GitBitch.Client\Agents\QuestionAgent.cs:line 34
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ClownCrew.GitBitch.Client.Agents.TalkAgent.<AskAsync>d__d`1.MoveNext() in c:\gitext\GitBitch\ClownCrew.GitBitch.Client\Agents\TalkAgent.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ClownCrew.GitBitch.Client.Commands.Application.ChangeNameCommand.<ExecuteAsync>d__9.MoveNext() in c:\gitext\GitBitch\ClownCrew.GitBitch.Client\Commands\Application\ChangeNameCommand.cs:line 32
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at ClownCrew.GitBitch.Client.App.<SetBitchNameAsync>d__5.MoveNext() in c:\gitext\GitBitch\ClownCrew.GitBitch.Client\App.xaml.cs:line 42
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at ClownCrew.GitBitch.Client.App.<OnStartup>d__0.MoveNext() in c:\gitext\GitBitch\ClownCrew.GitBitch.Client\App.xaml.cs:line 30
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at ClownCrew.GitBitch.Client.App.Main() in c:\gitext\GitBitch\ClownCrew.GitBitch.Client\obj\Debug\App.g.cs:line 0
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by gitsoft** [comment]
My theory is that the current code requires specific installations och that a specific version of system speech is required.
